server:
  port: 8082

spring:
  # 邮件配置
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: utf-8
    password: rbdeghrdfpkebjif
    username: zhangyu304@qq.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true

  rabbitmq:
    username: zhangyu
    password: zhangyu
    host: localhost
    port: 5672
    listener:
      simple:
        # 开启手动确认
        acknowledge-mode: manual


  redis:
    # 超时时间
    timeout: 10000ms
    # 服务器地址
    host: localhost
    # 服务器端口
    port: 6379
    # 数据库
    database: 0
    # 密码
    password: 123456
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 1024
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5


